---
title: "`r paste('Reporte Regresión Logística',project.name)`"
date: "`r format(Sys.Date(),'%B %d %Y')`"
output:
  html_document:
    df_paged: paged
    theme: cerulean
---


```{r setup,echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(knitr)
library(toolkitEntel)
safeLibrary(plyr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_knit$set(root.dir = "../")

```

# Informacion del modelo
##Dispersion parameters for `r info$family$family` family
```{r }
summary(calibration)->info
deviance.resid=summary(info$deviance.resid)
coefficients=info$coefficients
disp.par=data.frame(
  paste(round(info$null.deviance,1), "on", round(info$df.null,1), "degrees of freedom"),
  paste(round(info$deviance,1), "on", round(info$df.residual,1), "degrees of freedom"),
  as.character(round(info$aic,1)),as.character(info$iter)
  )
names(disp.par)=c("Null deviance:","Residual deviance:","AIC:","Fisher Scoring iterations:")
disp.par=as.data.frame(t(disp.par))
dis.par.aux = data.frame(Metric = rownames(disp.par), Value = disp.par$V1)
kable(x = dis.par.aux ,col.names = colnames(dis.par.aux),row.names = T,align = c('l','l'))

```

```{r, include = FALSE}
file.name = paste0(report.dir,"overall_of_",model.name)
fwrite(dis.par.aux, paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

## Deviance Residuals  
```{r }
print(deviance.resid)
```

## Coefficients
```{r }
kable(x = coefficients[order(coefficients[,"Pr(>|z|)"]),] ,col.names = colnames(coefficients),row.names = T,align = 'c')
```
```{r, include = FALSE}
coeff = data.frame(coefficients[order(coefficients[,"Pr(>|z|)"]),])
coeff.aux = data.frame(Variable = rownames(coeff),
                       Estimate = coeff$Estimate,
                       Std_error = coeff$Std..Error,
                       z_value = coeff$z.value,
                       Pr_z = coeff$Pr...z.. )
file.name = paste0(report.dir,"coeff_of_",model.name)
fwrite(coeff.aux, paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

##Gráfico
```{r }
plot(calibration)
```

# Features del Set de Entrenamiento 
```{r }
features=attr(calibration,"features")
file.name.features = paste0(report.dir,"features_", model.name)
cat(capture.output(print(features), file=paste0(file.name.features,".txt")))
```
```{r ,echo=TRUE}
#Variable a predecir
names(features$predicted_var)
#Variable llave
names(features$key)
#variables dummificadas
names(features$as_dummy)
#variables categoricas 
features$factors
#Variable con informacion extra
names(features$extra_info)
#variables calculadas con scripts
features$script
#Todas las variables predictoras 
names(features$predictor_var)

```

