---
title: "`r paste('Reporte Lasso',project.name)`"
date: "`r format(Sys.Date(),'%B %d %Y')`"
output:
  html_document:
    df_paged: paged
    theme: cerulean
---


```{r setup,echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(knitr)
library(toolkitEntel)
safeLibrary(plyr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_knit$set(root.dir = "../")

```

# Parametros del modelo

##Coeficientes
```{r }
df=as.data.frame(as.matrix(coef(calibration)))
df.aux = data.frame(Variable = rownames(df), Coef = df$`1`)
kable(x = df.aux ,col.names = colnames(df.aux),row.names = T,align = c('l','r'))
```
```{r, include = FALSE}
file.name = paste0(report.dir,"coef_of_",model.name)
fwrite(df.aux, paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

##Gráfico 
```{r }
plot(calibration)
```

# Features del Set de Entrenamiento 
```{r }
features=attr(calibration,"features")
<<<<<<< HEAD:templates/glmnet.cv_template.Rmd
file.name.features = paste0(report.dir,"/features_", model.name)
cat(capture.output(print(features),
                   file = paste0(file.name.features,".txt")
                   )
    )
=======
file.name.features = paste0(report.dir,"features_", model.name)
cat(capture.output(print(features), file=paste0(file.name.features,".txt")))
>>>>>>> bbabf6c41252831aabc6e685c216d9ecbb56ef46:reports/reports_templates/glmnet.cv_template.Rmd
```
```{r ,echo=TRUE}
#Variable a predecir
names(features$predicted_var)
#Variable llave
names(features$key)
#variables dummificadas
names(features$as_dummy)
#variables categoricas 
features$factors
#Variable con informacion extra
names(features$extra_info)
#variables calculadas con scripts
features$script
#Todas las variables predictoras 
names(features$predictor_var)

```

