---
title: "`r paste('Reporte Score',project.name)`"
date: "`r format(Sys.Date(),'%B %d %Y')`"
output:
  html_document:
    df_paged: paged
    theme: cerulean
---


```{r setup,echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(knitr)
library(toolkitEntel)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align = 'center')
knitr::opts_knit$set(root.dir = "../../")

```
# Información de modelos 

```{r }

kable(
  x = meta ,
  col.names = colnames(meta),
  row.names = F,
  align = 'c'
  )

```


# Visualización de resultados

##ROC 

```{r  }
df = ml.getAUC(score = scores)
kable(
x = df,
col.names = colnames(df),
row.names = F,
align = 'c'
)

```

```{r }
ml.plotROC(
  score = scores,
  title = "ROC",
  showAuc = F,
  legendTitle = legendTitle
  )
  

```

##Lift 
```{r, }
ml.plotLift(
  score = scores,
  quantiles = 100,
  cumulative = F,
  title = "Lift",
  quantileCuts = quantileCuts,
  legendTitle = legendTitle,
  xlab = "Percentil"
  )


```

```{r }
ml.plotLift(
  score = scores,
  quantiles = 100,
  cumulative = T,
  title = "Lift Acumulado",
  quantileCuts = quantileCuts,
  legendTitle = legendTitle,
  xlab = "Percentil"
  )
  

```
