---
title: "`r paste('Reporte Random Forest',project.name)`"
date: "`r format(Sys.Date(),'%B %d %Y')`"
output:
  html_document:
    df_paged: paged
    theme: cerulean
---


```{r setup,echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(knitr)
library(toolkitEntel)
safeLibrary(randomForest)
safeLibrary(plyr)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_knit$set(root.dir = "../")

```

# Parametros del modelo

```{r ,echo=TRUE}
calibration$ntree
```

```{r }
importance=calibration$importance[order(calibration$importance,decreasing = T),]
kable(x = importance ,col.names = colnames(calibration$importance),row.names = T,align = c('l','r'))
```

```{r, include = FALSE}
file.name = paste0(report.dir,"var_importance_of_",model.name)
importance.numeric = data.frame(predictors = rownames(calibration$importance),
                                MeanDecreaseGini = as.numeric(calibration$importance),
                                stringsAsFactors = FALSE)
fwrite(importance.numeric[order(importance.numeric$MeanDecreaseGini,decreasing = T),],
       paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

##Gráfico 
```{r }
plot(calibration)
```

# Features del Set de Entrenamiento 
```{r }
features=attr(calibration,"features")
file.name.features = paste0(report.dir,"features_", model.name)
cat(capture.output(print(features), file=paste0(file.name.features,".txt")))
```
```{r ,echo=TRUE}
#Variable a predecir
names(features$predicted_var)
#Variable llave
names(features$key)
#variables categoricas 
features$factors
#Variable con informacion extra
names(features$extra_info)
#variables calculadas con scripts
features$script
#Todas las variables predictoras 
names(features$predictor_var)

```

