---
title: "`r paste('Reporte Arbol de Decisión',project.name)`"
date: "`r format(Sys.Date(),'%B %d %Y')`"
output:
  html_document:
    df_paged: paged
    theme: cerulean
---


```{r setup,echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(knitr)
library(toolkitEntel)
safeLibrary(rpart)
safeLibrary(rpart.plot)
safeLibrary(plyr, load = F)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(fig.align='center')
knitr::opts_knit$set(root.dir = "../")

```

# Parametros del modelo
##calibration$parms

```{r ,echo=TRUE}
calibration$parms
```

##calibration$control
```{r }
options("scipen"=100, "digits"=4)
dfaux= plyr::ldply(calibration$control,x=x)
names(dfaux)=c("Name","Value")
kable(x = dfaux ,col.names = colnames(dfaux),row.names = F,align =c('l','r'))
```

```{r, include = FALSE}
file.name = paste0(report.dir,"control_of_",model.name)
fwrite(dfaux,paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

##variable importance
```{r}
aux = data.frame(calibration$variable.importance)

variable.importance = data.frame(Variables = rownames(aux),
                      Importance = aux[,1])
kable(x = variable.importance ,col.names = colnames(variable.importance),row.names = F, align = c('l','r'))

```
```{r, include = FALSE}
file.name = paste0(report.dir,"var_importance_of_",model.name)
fwrite(variable.importance,paste0(file.name,".csv"), sep = ";", dec = sep.dec)
```

##Gráfico 
```{r }
rpart.plot(calibration)
```

# Features del Set de Entrenamiento 
```{r }
features=attr(calibration,"features")
file.name.features = paste0(report.dir,"features_", model.name)
cat(capture.output(print(features), file=paste0(file.name.features,".txt")))
```
```{r ,echo=TRUE}
#Variable a predecir
names(features$predicted_var)
#Variable llave
names(features$key)
#variables categoricas 
features$factors
#Variable con informacion extra
names(features$extra_info)
#variables calculadas con scripts
features$script
#Todas las variables predictoras 
names(features$predictor_var)

```


